### PR TITLE
[DO NOT MERGE] Resolves web socket event communication between Sidekiq and Puma

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by scottkf** [comment]
good to close out @ashish91 ?

**Comment by ghost** [comment]
@scottkf This fixes websocket issues on staging and local. This will eventually be merged. I am testing on production apps. These are not backward compatible changes so to promote this we need to follow:

- In our apps point Gemfile to this branch and merge cloudlogistics to master.
- Promote the change to all apps.
- Merge this branch to master while keeping the branch.
- Update cloudlogistics Gemfile to point websocket-rails to master.
- Promote the change to all apps.
- Delete this branch once it's promoted to all apps.

Let me know if we should follow some other process to promote this.

**Comment by ghost** [comment]
Correction I tested these changes with master and they're working properly. These are backward compatible changes. We can merge this once the verification of https://github.com/cloudlogistics/cloudlogistics/pull/6746 is complete.

**Comment by prathamesh-sonpatki** [comment]
@ashish91 Please merge this as per your previous comment.

**Comment by ghost** [comment]
@prathamesh-sonpatki I thought it'll be better to merge this on promoting CL repo changes to production apps since we also need to merge https://github.com/cloudlogistics/base-docker-image/pull/13 when CL repo changes are promoted to production apps. The CL [master](https://github.com/cloudlogistics/cloudlogistics/blob/master/cl_system/Gemfile#L39) is already pointing to this branch so merging this immediately is not required.
Please let me know your thoughts on this.

**Comment by prathamesh-sonpatki** [comment]
Sounds good.

**Comment by prathamesh-sonpatki** [comment]
@ashish91 Can this be merged now?

**Comment by ghost** [comment]
@prathamesh-sonpatki Not yet. I discussed with @prajakta-tambe about this, some apps are yet to be deployed. @prajakta-tambe Can you pls confirm ?

**Comment by prajakta-tambe** [comment]
@ashish91 @prathamesh-sonpatki Yes. We still have a few apps on custom branches and without https://github.com/cloudlogistics/cloudlogistics/pull/6746/files changes.

**Pull request merged**
